<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-02 at 22:05:44.
 */
require_once '..\config\class.conexion.php';
class ConexionTest extends PHPUnit_Framework_TestCase {

    protected $object;

    protected function setUp() {
        $this->object = new Conexion();
    }
           
    public function test__construct(){
        $actual=$this->object->__construct();
        $result='Conectado';
        $this->assertEquals($actual, $result);
    }
    
    public function tearDown() {
        $this->object->close();
    } 

}
